### ISSUE TITLE
Folders in `/opt/conda/pkgs` in conflict with newer versions of conda

### ISSUE THREAD

**Issue by ostrokach** [conda-forge/docker-images#62]
Several of my builds have started failing with the most recent `condaforge/linux-anvil` docker image (for example, see [here](https://gitlab.com/kimlab/kmbio/-/jobs/50095796)).

<details>
<summary><code>Traceback (most recent call last):</code></summary>
<pre>
  File "/opt/conda/bin/conda-build", line 11, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 413, in main
    execute(sys.argv[1:])
  File "/opt/conda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 404, in execute
    verify=args.verify)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/api.py", line 188, in build
    need_source_download=need_source_download, config=config, variants=variants)
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1913, in build_tree
    notest=notest,
  File "/opt/conda/lib/python3.6/site-packages/conda_build/build.py", line 1053, in build
    is_conda=m.name() == 'conda')
  File "/opt/conda/lib/python3.6/site-packages/conda_build/environ.py", line 812, in create_env
    execute_actions(actions, index, verbose=config.debug)
  File "/opt/conda/lib/python3.6/site-packages/conda/common/io.py", line 441, in decorated
    return f(*args, **kwds)
  File "/opt/conda/lib/python3.6/site-packages/conda/plan.py", line 392, in execute_actions
    execute_instructions(plan, index, verbose)
  File "/opt/conda/lib/python3.6/site-packages/conda/plan.py", line 599, in execute_instructions
    cmd(state, arg)
  File "/opt/conda/lib/python3.6/site-packages/conda/instructions.py", line 64, in PROGRESSIVEFETCHEXTRACT_CMD
    progressive_fetch_extract.execute()
  File "/opt/conda/lib/python3.6/site-packages/conda/core/package_cache.py", line 590, in execute
    raise CondaMultiError(exceptions)
conda.CondaMultiError: [Errno 21] Is a directory: '/opt/conda/pkgs/setuptools-38.4.0-py36_0'
</pre>
</details>

<br>

I think the reason is that I am using the most recent version of conda (`conda update -n root conda conda-build`), and the packages inside the `/opt/conda/pkgs` folder are somehow too old for conda to handle them gracefully. Running `rm -rf /opt/conda/pkgs/*` before `conda build .` seems to fix the issue.

Maybe `rm -rf /opt/conda/pkgs/*` should be included in the `Dockerfile`?  This would have an additional advantage of making the docker image smaller.

**Comment by ostrokach** [comment]
Actually, `conda clean -yq --all` does not fix the problem. I'll close the issue until I'm sure it's caused by the `condaforge/linux-anvil` docker container...

**Comment by jakirkham** [comment]
Is this still an issue @ostrokach?
